apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: {{values.clusterRef}}
  labels:
    backstage.io/kubernetes-id: {{values.component_id}}
spec:
  forProvider:
    region: eu-central-1
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      subnetIdRefs:
        - name: {{values.networkRef}}-sn0
        - name: {{values.networkRef}}-sn1
    roleArnRef:
      name: {{values.component_id}}-controlplane
  writeConnectionSecretToRef:
    name: {{values.component_id}}-eks-kubeconfig
    namespace: crossplane-system
  providerConfigRef:
    name: aws-stack-template-provider
