create-argocd-application:
    script: |
        curl -v -k --fail --location \
        --request POST '${{values.argocd_url}}/api/v1/applications' \
        --header 'Content-Type: application/json' \
        --header 'Cookie: argocd.token=${{values.argocd_token}}' \
        --data-raw '{
            "metadata": {
                "name": "${{values.component_id}}"
            },
            "spec": {
                "source": {
                    "repoURL": "${{values.storePath}}.git",
                    "path": "charts/"
                },
                "destination": {
                    "namespace": "${{values.component_id}}",
                    "server": "https://kubernetes.default.svc"
                },
                "syncPolicy": {
                    "syncOptions": [
                        "CreateNamespace=true"
                    ],
                    "automated": {
                        "allowEmpty": true,
                        "prune": false,
                        "selfHeal": false
                    }
                }
            }
        }'
