apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  description: ${{values.description}}
  annotations:
    github.com/project-slug: ${{values.destination.git.owner + "/" + values.destination.git.name}}
    backstage.io/techdocs-ref: url:{{values.storePath}}
    argocd/app-name: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner}}
