apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{cookiecutter.component_id | dump}}
  description: ${{cookiecutter.description | dump}}
  annotations:
    github.com/project-slug: ${{cookiecutter.destination.git.owner + "/" + cookiecutter.destination.git.name}}
    backstage.io/techdocs-ref: url:${{cookiecutter.storePath}}
    argocd/app-name: ${{cookiecutter.component_id | dump}}
    backstage.io/kubernetes-id: ${{cookiecutter.component_id | dump}}
spec:
  type: service
  lifecycle: experimental
  owner: $${{values.owner}}
