apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: { { values.component_id | jsonify } }
  description: { { values.description | jsonify } }
  annotations:
    github.com/project-slug:
      { { values.destination.git.owner + "/" + values.destination.git.name } }
    backstage.io/techdocs-ref: url:{{values.storePath}}
    argocd/app-name: { { values.component_id | jsonify } }
    backstage.io/kubernetes-id: { { values.component_id | jsonify } }
spec:
  type: service
  lifecycle: experimental
  owner: { { values.owner | jsonify } }
